theme: jekyll-theme-cayman
title: CERRES
description: Chemical Reaction and Reactor Engineering Simulations
show_downloads: true
gems:
  - jekyll-sitemap
plugins:
  - jekyll-sitemap
  
github:
  zip_url: http://example.com/download.zip
  another_url: google.com
